apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: go-microservices
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: go-microservices
  filterTags: 
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc
    