apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: go-micro
  namespace: go-microservice
spec:
  releaseName: go-microservice-release
  chart:
    spec:
      chart: go-microservice
      sourceRef:
        kind: HelmRepository
        name: go-microservice
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      name: gh05tsh/go-rest-api # {"$imagepolicy": "flux-system:go-microservices:name"}
      tag: main-24735f2d-20220302T215301-1646171893 # {"$imagepolicy": "flux-system:go-microservices:tag"}
