apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: go-micro
  namespace: go-microservice
spec:
  chart:
    spec: 
      version: ">=0.2.0"
    values: 
      replicaCount: 3